name = "EnergyCommunity"
uuid = "2f2d8a28-e724-42c4-aa4e-51fe4e6b7a61"
authors = ["davide-f <fioritidavidesubs@gmail.com>"]
version = "0.2.2"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LayeredLayouts = "f4a74d36-062a-4d48-97cd-1356bad1de4e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PointEstimateMethod = "f5532426-4504-4a0a-b768-abad0680b22a"
SankeyPlots = "8fd88ec8-d95c-41fc-b299-05f2225f2cc5"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TheoryOfGames = "eb50afb4-6f20-4b37-9b66-473e668300bf"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10"
DataFrames = "1"
DataStructures = "0.19.3"
Distributions = "0.25.122"
ExportAll = "0.1"
FileIO = "1"
Format = "1"
Formatting = "0.4"
JLD2 = "0.4.55"
JuMP = "1.29.3"
LayeredLayouts = "0.2"
MathOptInterface = "1.0"
Parameters = "0.12.3"
Plots = "1, 2"
PointEstimateMethod = "0.1.3"
SankeyPlots = "0.2.2"
StatsPlots = "0.15"
TheoryOfGames = "0.1"
XLSX = "0.9, 0.10"
YAML = "0.4"
julia = "1"
