name = "EnergyCommunity"
uuid = "2f2d8a28-e724-42c4-aa4e-51fe4e6b7a61"
authors = ["davide-f <fioritidavidesubs@gmail.com>"]
version = "0.3.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExportAll = "ad2082ca-a69e-11e9-38fa-e96309a31fe4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SankeyPlots = "8fd88ec8-d95c-41fc-b299-05f2225f2cc5"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TheoryOfGames = "eb50afb4-6f20-4b37-9b66-473e668300bf"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10"
DataFrames = "1"
ExportAll = "0.1"
FileIO = "1"
Format = "1"
JuMP = "1"
MathOptInterface = "1.0"
Plots = "1, 2"
SankeyPlots = "0.2.2, 0.3"
StatsPlots = "0.15"
TheoryOfGames = "0.1, 0.2"
XLSX = "0.9, 0.10"
YAML = "0.4"
julia = "1"
